name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Docker image name (e.g., roshankumar402/my-image-name)'
        required: true
      container_name:
        description: 'Docker container name'
        required: true
      port:
        description: 'Port to open on the host'
        required: true
      tag_name:
        description: 'Docker image tag (e.g., latest)'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        docker build . --file Dockerfile --tag ${{ github.event.inputs.image_name }}:${{ github.event.inputs.tag_name }}

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u roshankumar402 --password-stdin

    - name: Push Docker Image
      run: docker push ${{ github.event.inputs.image_name }}:${{ github.event.inputs.tag_name }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: SSH into the Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull ${{ github.event.inputs.image_name }}:${{ github.event.inputs.tag_name }}
          docker stop ${{ github.event.inputs.container_name }} || true
          docker rm ${{ github.event.inputs.container_name }} || true
          docker run -d --name ${{ github.event.inputs.container_name }} -p ${{ github.event.inputs.port }}:80 ${{ github.event.inputs.image_name }}:${{ github.event.inputs.tag_name }}
