name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: |
        docker build . --file Dockerfile --tag roshankumar402/my-image-name:latest

    - name: Show Docker Image Tag
      run: echo "Docker Image Tag:roshankumar402/my-image-name:latest"

  push:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker Image
      run: docker push roshankumar402/my-image-name:latest

  deploy:
    runs-on: ubuntu-latest
    needs: push

    steps:
    - name: SSH into the server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull roshankumar402/my-image-name:latest
          docker stop my-container-name || true
          docker rm my-container-name || true
          docker run -d --name my-container-name -p 80:80 roshankumar402/my-image-name:latest
