name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        docker build . --file Dockerfile --tag roshankumar402/my-image-name:latest

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u roshankumar402 --password-stdin

    - name: Push Docker Image
      run: docker push roshankumar402/my-image-name:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: SSH into the Server
      uses: appleboy/ssh-action@v0.6.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull roshankumar402/my-image-name:latest
          docker stop my-container-name || true
          docker rm my-container-name || true
          docker run -d --name my-container-name -p 80:80 roshankumar402/my-image-name:latest
